### ISSUE TITLE
NullReference exception when access token is null in LoginAsync (happens when user hits cancel button)

### ISSUE THREAD

**Issue by f2bo** [facebook-csharp-sdk/facebook-winclient-sdk#21]
In the LoginAsync method of the FacebookSessionClient class, if the user cancels the login request, no access token is produced. Regardless of the outcome, the method always attempts to use the AccessToken to construct an instance of the FacebookClient class. When this token is null, it fails with an ArgumentNullException. 

``` C#
...
var session = FacebookSessionCacheProvider.Current.GetSessionData();
if (session == null)
{
    // Authenticate
    var authResult = await PromptOAuthDialog(permissions, WebAuthenticationOptions.None);

    // ArgumentNullException thrown in FacebookClient when null token is provided here
    FacebookClient client = new FacebookClient(authResult.AccessToken);
...
```

**Comment by sanjeevdwivedi** [comment]
The LoginAsync API is deprecated. Use the Session.ActiveSession.LoginWithBehavior API which does not suffer fromm this issue.
