### ISSUE TITLE
Invalid Facebook ID cached when renewing access token

### ISSUE THREAD

**Issue by f2bo** [facebook-csharp-sdk/facebook-winclient-sdk#22]
In the LoginAsync method of the FacebookSessionClient, whenever a cached access token expires, it's renewed by prompting with the OAuth dialog again. If the user changes the identity used to log in, the new session is cached, but the Facebook ID is never requested again, so the session data contains an access token for the new user but the Facebook ID corresponds to the previous user.

```C#
...
// Prompt OAuth dialog if force renew is true or
// if new permissions are requested or 
// if the access token is expired.
if (force || newPermissions || session.Expires <= DateTime.UtcNow)
{
    var authResult = await PromptOAuthDialog(permissions, WebAuthenticationOptions.None);
    if (authResult != null)
    {
        // THIS IS REUSING THE PREVIOUS SESSION OBJECT WITH A STALE ID
        session.AccessToken = authResult.AccessToken;
        session.Expires = authResult.Expires;
    }
}
...
```

**Comment by sanjeevdwivedi** [comment]
This issue has been fixed with the refactoring of the SDK.
