### ISSUE TITLE
LoginAsync loop

### ISSUE THREAD

**Issue by galvesribeiro** [facebook-csharp-sdk/facebook-winclient-sdk#29]
Hi,

I'm trying to use App.FacebookSessionClient.LoginAsync from the WP7 client sample.

It keeps looping in the loginAsync method and never set the FacebookSession object since a InvalidOperationException is throw by this method.

I added this IF only to check the progress:

if(App.FacebookSessionClient.LoginInProgress)
                    {
                        continue;
                    }

And I noticed that the login is always in progress and never end after the webview is dismissed with the login.

How can I get it working. 

Thanks!

**Comment by sanjeevdwivedi** [comment]
With the rewrite of the LoginWithBehavior and removing the LoginAsync, this issue has been fixed. Try the Session.ActiveSession.LoginWithBehavior method to login.

**Comment by galvesribeiro** [comment]
Hi,

When this was implemented? Is there a new release? The current sdk still use grap v1.1 while it is comming to deprecate really soon. 

Thanks

**Comment by sanjeevdwivedi** [comment]
Facebook.dll already has 2.1 support in the alpha branch. Facebook.Client.dll had this functionality added just a week ago.

-----Original Message-----
