### ISSUE TITLE
FacebookSessionClient error

### ISSUE THREAD

**Issue by masterdimar** [facebook-csharp-sdk/facebook-winclient-sdk#32]
The code

public static FacebookSessionClient FacebookSessionClient = new FacebookSessionClient(Constants.FacebookAppId);

always return the error "Attempt to access the method failed: System.Reflection.Assembly.GetName()"

**Comment by sanjeevdwivedi** [comment]
@masterdimar @prabirshrestha This function was used in an analytics piece. It has since been taken out. Closing the bug since it is not applicable anymore.
