### ISSUE TITLE
0.9.91-alpha closes and re-opens the app when doing LoginWithBehavior with LoginBehaviorWebViewOnly

### ISSUE THREAD

**Issue by neilmca** [facebook-csharp-sdk/facebook-winclient-sdk#61]
Issue is described here
http://stackoverflow.com/questions/28429483/facebook-client-0-9-91-alpha-is-a-step-backwards-for-logging-in-to-fb

**Comment by sanjeevdwivedi** [comment]
Replied on stackoverflow already. Closing.
